BEGIN TRANSACTION;
CREATE TABLE keyRange (
  id INT AUTO_INCREMENT PRIMARY KEY,
  job_id INT NOT NULL,
  fromKey VARCHAR(255) NOT NULL,
  toKey VARCHAR(255) NOT NULL,
  totalKeys INT NOT NULL,
  tried BOOLEAN NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_job
  FOREIGN KEY (job_id)
    REFERENCES job(id)
);
CREATE TABLE job (
    id INT AUTO_INCREMENT PRIMARY KEY,
    crypted VARCHAR(255) NOT NULL,
    plain VARCHAR(255),
    status TINYINT NOT NULL DEFAULT 0,
    key VARCHAR(255),
    priority TINYINT NOT NULL DEFAULT 255,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
